### ISSUE TITLE
Poster Work

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#59] opened 2024-03-28 15:17 UTC
Issue associated with working on the poster outside of class

**Comment by alejmedinajr** [comment] 2024-03-28 15:17
Starting on this now

**Comment by alejmedinajr** [comment] 2024-03-28 15:47
Just did 30 mins of work on the post, included some resizing and coming up with some reasons why users may want to use SNITCH

**Comment by alejmedinajr** [comment] 2024-03-28 16:19
Did 30 more minutes of work on the poster, I added three screen clips of code that we had in the TODO blocks. These are screen clips I thought were more interesting for the poster (could be changed). Also, I added comments for each clip to explain what each was, with an additional note of how they could be used together.

**Comment by noahzamarripa** [comment] 2024-03-31 23:04
picking this up

**Comment by noahzamarripa** [comment] 2024-03-31 23:37
The original logo file thats in our drive is a pdf of the graphic/text on a portrait oriented page, so I basically am taking the text off of the page so we can have it on the poster

**Comment by noahzamarripa** [comment] 2024-04-01 00:53
I pulled the branch from issue 51 as that is the one that is furthest along in regard to the overall flow and UI and I am having issues running the react app on web. The issue is 'missing app configuration value' and have been trying to fix this. Will update soon

**Comment by noahzamarripa** [comment] 2024-04-01 02:23
The api key needs to be hidden and used as a variable in config file so a .env file is to be made locally with the key assigned to the variable and it should work but has not for some reason. I tried to just put the api key straight into the firebase.js file and I get the same message. Can't progress until this is resolved. 
![IMG_3212](https://github.com/alejmedinajr/AI-Detector/assets/91333145/687d0308-f4c2-45f6-a09f-f5c4b99a1cde)

**Closed** 2024-04-07 18:35 UTC
Labels: Design
